# Generated by Django 4.1.3 on 2022-12-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('rasm', models.CharField(max_length=255)),
                ('context', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tanlov', models.CharField(max_length=60)),
            ],
        ),
    ]
